version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - ~/.docker-compose/postgres:/var/db/postgres
